[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  environment = [
    "REACT_APP_LOCAL_BACKEND",
    "REACT_APP_PROD_BACKEND",
    "NPM_FLAGS",
    "NODE_ENV",
    "REACT_APP_API_URL"
  ]
